### ISSUE TITLE
Missing requests library in install_requires

### ISSUE THREAD

**Issue by forsberg** [marcosschroh/python-schema-registry-client#69]
**Describe the bug**
The requests library is imported in `schema_registry/client/client.py` but is not listed as an install_requires in `setup.py` 

**To Reproduce**
```
$ mkvirtualenv python-schema-registry-client
$ git clone git@github.com:marcosschroh/python-schema-registry-client.git
$ cd python-schema-registry-client
$ pip install -e .
Obtaining file:///home/forsberg/dev/python-schema-registry-client
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting fastavro
  Using cached fastavro-0.24.0-cp37-cp37m-manylinux2010_x86_64.whl (1.4 MB)
Collecting httpx
  Using cached httpx-0.14.1-py3-none-any.whl (60 kB)
Collecting pytz
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting chardet==3.*
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna==2.*
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting rfc3986<2,>=1.3
  Using cached rfc3986-1.4.0-py2.py3-none-any.whl (31 kB)
Collecting httpcore==0.10.*
  Using cached httpcore-0.10.1-py3-none-any.whl (47 kB)
Collecting certifi
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting sniffio
  Using cached sniffio-1.1.0-py3-none-any.whl (4.5 kB)
Collecting h11<0.10,>=0.8
  Using cached h11-0.9.0-py2.py3-none-any.whl (53 kB)
Installing collected packages: pytz, fastavro, chardet, idna, rfc3986, h11, sniffio, httpcore, certifi, httpx, python-schema-registry-client
  Running setup.py develop for python-schema-registry-client
Successfully installed certifi-2020.6.20 chardet-3.0.4 fastavro-0.24.0 h11-0.9.0 httpcore-0.10.1 httpx-0.14.1 idna-2.10 python-schema-registry-client pytz-2020.1 rfc3986-1.4.0 sniffio-1.1.0
$ git log -1
commit a43871334d13921bdcb90df4cc33ef906021a93c (HEAD -> master, origin/master, origin/HEAD)
Author: Marcos Schroh <schrohm@gmail.com>
Date:   Thu Aug 13 10:18:52 2020 +0200

    fix: setup.cfg added. pyproject.toml added. test creation of client with httpx config added (#68)

$ python
Python 3.7.5 (default, Apr 19 2020, 20:18:17) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from schema_registry.client import SchemaRegistryClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/forsberg/dev/python-schema-registry-client/schema_registry/client/__init__.py", line 2, in <module>
    from schema_registry.client.client import SchemaRegistryClient  # noqa
  File "/home/forsberg/dev/python-schema-registry-client/schema_registry/client/client.py", line 8, in <module>
    from requests import utils as requests_utils
ModuleNotFoundError: No module named 'requests'
```

**Expected behavior**
Well, not a ModuleNotFoundError :-)

**Comment by marcosschroh** [comment]
Thanks @forsberg . The `requests` requirement was installed through `httpx` but the library changed the `api` a few days ago. I will try to remove the `requests` requirements as well.
